### ISSUE TITLE
Scala 2 libray TASTy compatibility

### ISSUE THREAD

**Issue by nicolasstucki** [outr/spice#142]
We found that this library does not work with the current Scala 2 library TASTy 

* See error in: https://github.com/scala/scala3/pull/19588#issuecomment-1925463405
* See what is the Scala 2 library TASTy in: https://contributors.scala-lang.org/t/scala-2-libary-tasty/6602
* Solution to one of the issues: https://github.com/scala/scala3/issues/19616#issuecomment-1929528049

Please help us minimize this issue to see if it is something expected, a bug in this code base, or a bug in the compiler/library.

**Comment by darkfrog26** [comment]
@nicolasstucki I don't see anything that should change in Spice, as it's clearly a bug in TASTy not properly supporting `+=` on `Map`.

**Comment by nicolasstucki** [comment]
> as it's clearly a bug in TASTy not properly supporting += on Map.

The issue in [#19616 is ](https://github.com/scala/scala3/issues/19616) is about an error reporting issue when using TASTy. But it hides a real bug. In this case the bug is the use of `()` for `sb.toString`. Now that Scala 3 rules apply on the library, `sb.toString()` is not allowed anymore. See https://github.com/scala/scala3/issues/19616#issuecomment-1929528049.

**Comment by darkfrog26** [comment]
This should be fixed now. Let me know if you have any additional problems.
